{% set name = "igor" %}
{% set version = "0.3" %}
{% set sha256 = "b04ac38c68fb81cf3167a9981dc5a20379112d40268bb72c5a8514dc8051abba" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - git_patch.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - igorbinarywave = bin.igorbinarywave:main
    - igorpackedexperiment = bin.igorpackedexperiment:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - matplotlib-base
    - numpy

test:
  imports:
    - igor.binarywave
    - igor.packed
    - igor.igorpy
  commands:
    - igorbinarywave --help
    - igorpackedexperiment --help

about:
  home: http://blog.tremily.us/posts/igor
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Python parsers for WaveMetrics Igor Binary Waves and Packed Experiment files
  description: |
    Python parsers for Igor Binary Waves (.ibw) and Packed Experiment
    (.pxp) files written by WaveMetrics' IGOR Pro software.
  doc_url: http://git.tremily.us/?p=igor.git;a=blob_plain;f=README;hb=HEAD
  dev_url: http://blog.tremily.us/posts/igor
